GROUP_REPLACEMENT_OPTIONS = {
    "day": ["{day}"],
    "week": ["{week}"],
    "degree Celsius": ["{degree Celsius}"],
    "gray": ["{gray}"],
    "hours": ["{hour}"],
    "minutes": ["{minute}"],
    "Centi{gray}": ["{Centigray}"],
    "Col-0-PhyD": ["Col-0 PhyD", "Columbia ecotype with a mutation in phytochrome D (PhyD)"],
    "FLT": ["Space Flight"],
    "GC": ["Ground Control"],
    "Alight": ["4-6 umoles m-2 s-1 total light", "specimen grown in Ambient light"],
    "dark": ["Light-activated for 4 hours, then dark-grown", "specimen grown in darkness"],
    "RR1": ["SpaceX-4 (RR1)"],
    "RR3": ["Spacex-8 (RR3)"],
    "BSL": ["Basal Control"],
    "VIV": ["Vivarium Control"],
    "noERCC": ["Without Spike-in"],
    "wERCC": ["With Spike-in"],
    "HLLC": ["Hindlimb Loaded Control"],
    "HLU": ["Hindlimb Unloaded", "Hind Limb Unloading"],
    "IRC": ["Non-irradiated"],
    "IR": ["Irradiated with 0.04 Gy 57Co"],
    "1mon": ["1 {month}"],
    "4mon": ["4 {month}"],
    "Hindlimb Loaded Unloaded": ["Hindlimb Unloaded"],
    "1G": ["1G by centrifugation", "1G centrifuge", "1G Control"],
    "JC": ["JAXA Chow"],
    "wFOS": ["with FOS"],
    "1": ["1 {day}"],
    "30": ["30 {day}"],
    "60": ["60 {day}"],
    "DI": ["Dry Ice"],
    "LN2": ["Liquid Nitrogen", "Liquid nitrogen"],
    "1y": ["long term (around 1 year)"],
    "3d": ["short term (3 days)"],
    "10cGY Cs 137": ["10cGy & Cs 137"],
    "1cGY Cs 137": ["1cGy & Cs 137"],
    "2.5cGY Cs 137": ["2.5cGy & Cs 137"],
    "5cGY Cs 137": ["5cGy & Cs 137"],
    "7.5cGY Cs 137": ["7.5cGy & Cs 137"],
    "Col-0": ["WT Col-0", "Arabidopsis thaliana Columbia-0 ecotype"],
    "Cvi-0": ["WT Cvi-0", "Cape Verde Islands"],
    "Ler-0": ["WT Ler-0", "Landsberg ecotype"],
    "Ws-2": ["WT Ws-2", "Wassilewskija-2"],
    " ": ["nan"],
    "MESH:Space Flight": ["Space Flight"],
    "{day}": ["day"],
    " 5": ["5 {day}"],
    " 26": ["26 {hour}"],
    " 22": ["22 {day}"],
    "14": ["14 {degree Celsius}"],
    "24": ["24 {degree Celsius}"],
    "19": ["19 {degree Celsius}"],
    "suG": ["uG in RPM", "uG", "simulated microgravity"],
    "50 kPa": ["50,000 {pascal}"],
    "50+O2 to 21 kPa": ["50,000 pascal + O2 to 21,000 {pascal}"],
    "97 kPa": ["97,000 {pascal}"],
    "cells": ["sample collection - spleen cells", "material type - cell line"],
    "ss-tissues": ["sample collection - whole spleen", "tissues that underwent size selection during library prep (after extraction)"],
    "tissues": ["sample collection - spleen tissue", "more than 1 tissue from 1 animal was pooled"],
    "uG": ["uG with clinorotation", "Microgravity"],
    "3G": ["3G with Centrifugation"],
    "pFLT": ["Parabolic Flight"],
    "pGC": ["Ground Control Parabolic Flight"],
    "soFLT": ["Suborbital Ballistic Rocket Flight"],
    "soGC": ["Ground Control Suborbital Ballistic Rocket Flight"],
    "CTRL": ["Control"],
    "RL": ["Re-loaded"],
    "TRHLLC": ["Tail Restrained Hind Limb Loaded Control"],
    "HG": ["Hypergravity"],
    "act": ["Activated"],
    "nonact": ["Non-activated"],
    "Tcells": ["T cells"],
    "Dmel": ["Drosophila melanogaster"],
    "Can-S": ["Canton-Special"],
    "Ecol": ["Escherichia coli"],
    "Bbas": [" Beauveria bassiana"],
    "infdw": ["infected with"],
    "uninfd": ["Uninfected"],
    "sham-infd": ["Sham infected"],
    "Atha": ["Arabidopsis thaliana"],
    "Brap": ["Brassica rapa"],
    "nipp": ["Nipposinica"],
    "Etsl": ["Etiolated seedlings"],
    "UdCC": ["Undifferentiated cell culture"],
    "BA1": ["BRIC A PDFU-1"],
    "BA2": ["BRIC A PDFU-2"],
    "BA3": ["BRIC A PDFU-3"],
    "BA4": ["BRIC A PDFU-4"],
    "BA5": ["BRIC A PDFU-5"],
    "BB2": ["BRIC B PDFU-2"],
    "BB3": ["BRIC B PDFU-3"],
    "BB4": ["BRIC B PDFU-4"],
    "BB5": ["BRIC B PDFU-5"],
    "BG1": ["BRIC G PDFU-1"],
    "BG2": ["BRIC G PDFU-2"],
    "BG3": ["BRIC G PDFU-3"],
    "WT": ["Wild-type"],
    "MUT": ["Mutant"],
    "wo": ["Whole Organism"],
    "LVR": ["Liver"],
    "SPL": ["Spleen"],
    "ADR": ["Adrenal Glands", "Adrenal Gland"],
    "KDN": ["Kidney"],
    "GST": ["Gastrocnemius"],
    "EDL": ["Extensor Digitorum Longus"],
    "SLS": ["Soleus"],
    "TA": ["Tibialis Anterior"],
    "SM": ["Skeletal Muscle"],
    "SKN": ["Skin"],
    "Quad": ["Quadricep"],
    "MG": ["Mammary Gland"],
    "TMS": ["Thymus"],
    "RR": ["Rodent Research"],
    "MHU": ["Mouse Habitat Unit"],
    "FS": ["Freezing Study"],
    "JAXA": ["Japan Aerospace Exploration Agency"],
    "CC": ["Cohort Control"],
    "C#": ["Cohort Number"],
    "LAR": ["Live Animal Return"],
    "ISS-T": ["ISS Terminal Animal"],
    "NuRFB": ["Nutrient Upgraded Rodent Food Bar"],
    "BSP": ["Biospecimen Sharing Program"],
    "LSDA": ["Life Science Data Archive"],
    "ALSDA": ["Ames Life Science Data Archive"],
    "ACF": ["Animal Care Facility"],
    "LLU": ["Loma Linda University"],
    "KSC": ["Kennedy Space Center"],
    "RNA": ["Ribonucleic acid"],
    "DNA": ["Deoxyribonucleic acid"],
    "PRT": ["Protein"],
    "ALQ": ["Aliquot"],
    "RNAlat": ["RNA later"],
    "RIN": ["RNA integrity number"],
    "DIN": ["DNA integrity number"],
    "MIX1": ["ERCC Spike In mix 1"],
    "MIX2": ["ERCC Spike In mix 2"],
    "LNG": ["Lung"],
    "BLD": ["Blood"],
    "WB": ["Whole Blood"],
    "WBCs": ["White Blood Cells"],
    "RBCs": ["Red Blood Cells"],
    "leu": ["Leukocytes"],
    "EYE": ["Eye"],
    "CLN A61": ["Colon"],
    "FCS": ["Feces"],
    "RTN": ["Retina"],
    "BRN": ["Brain"],
    "L": ["Left"],
    "R": ["Right"],
    "D": ["Dorsal"],
    "V": ["Ventral"],
    "F": ["Femoral"],
    "OD": ["Optical Density"],
    "URR": ["Universal Reference RNA"],
    "UHRR": ["Universal Human Reference RNA"],
    "UMRR": ["Universal Mouse Reference RNA"],
    "Gspe": ["Genus species"],
    "C57-6J": ["C57BL/6 mouse from Jackson Labs"],
    "OR": ["Oregon R"],
    "act2-3": ["vegetative actin mutant Arabidopisis thaliana"],
    "C57-10J": ["C57BL/10J mouse from Jackson Labs"],
    "sShoots": ["seedling shoots"],
    "C57-6IBCh": ["C57BL/6 mouse from Shemyakin & Ovchinnikov Institute of Bioorganic Chemistry, Russia"],
    "C57-6T": ["C57BL/6 mouse from Taconic Biosciences"],
    "I": ["Upon euthanasia"],
    "C": ["Carcass", "Celsius"],
    "LD": ["Longissimus Dorsi Muscle"],
    "TNG": ["Tongue"],
    "ARG1-KO": ["A. thaliana Col-0 knock-out line deficient in the gene encoding Altered response to gravity-1"],
    "JkTcells": ["Jurkat T cells"],
    "C57-6CR": ["C57BL/6 mouse from Charles River"],
    "os-ind": ["osteo-induced"],
    "not-ind": ["not induced"],
    "BMSC": ["Bone Marrow Stromal Cells"],
    "MSCs": ["Mesenchymal Stem Cells"],
    "EMF": ["treated with electromagnetic fields"],
    "LDC": ["Large Diameter Centrifuge"],
    "RPoM": ["Random Positioning Machine"],
    "ML": ["Magnetic Levitator"],
    "do": ["days old"],
    "yo": ["years old"],
    "oLDC": ["Outside the Large Diameter Centrifuge"],
    "oRPoM": ["Outside the Random Positioning Machine"],
    "oML": ["Outside the Magnetic Levitator"],
    "YR": ["Gamma Radiation"],
    "HZE": ["HZE ionizing radiation"],
    "ATM1": ["mutant defective in the DSB-sensing protein kinase ATM"],
    "Gy": ["Gray"],
    "sl": ["seedling"],
    "sl-pool": ["pool of 2 or more whole seedlings"],
    "lvCMC": ["left ventricular cardiomyocytes"],
    "MCL": ["medial collateral ligament"],
    "Rnor": ["Rattus norvegicus"],
    "Sx": ["Surgery"],
    "noSx": ["No surgery"],
    "shamSx": ["Sham surgery"],
    "bildisMCL": ["Bilateral disruption of the medial collateral ligament"],
    "lpup": ["late pupae"],
    "dT": ["delta Temperature"],
    "NOdT": ["no change in Temperature"],
    "ltdO2": ["limited Oxygen"],
    "normO2": ["Normal Oxygen levels"],
    "Ws-0": ["Wassilewskija-0"],
    "Ws": ["Wassilewskija"],
    "suppO2": ["supplemented with Oxygen"],
    "kPa": ["kilopascals"],
    "Hml-Gal4-UAS-GFP": ["Hemolectin-GAL4 crossed with UAS-GFP to make a transgenic line in Dmel"],
    "TKSC": ["Tsukuba Space Center"],
    "N2": ["Bristol N2"],
    "ISS": ["International Space Station"],
    "RWV": ["Rotating Wall Vessel"],
    "2T3": ["cells osteoblast cell line 2T3"],
    "LS292": ["C.elegans strain representing a dys1(cx18) mutant"],
    "HF": ["Hair Follicles"],
    "inFLT": [" in spaceflight"],
    "preFLT": ["pre spaceflight"],
    "postFLT": ["post spaceflight"],
    "BAL-SL": ["BALB/c mouse from Simonsen Labs"],
    "BAL-JL": ["BALB/c mouse from Jackson Laboratory"],
    "BAL-TAL": ["BALB/c mouse from Taconic Animal Laboratory"],
    "4T1-Tumor": ["Flank tumor derived from the 4T1 murine mammary carcinoma cell line that was generated from a BALB/cfC3H mouse"],
    "1D11": ["Antibody that binds to TGFB and thus inhibits function"],
    "IsoCTRL": ["Isotype control"],
    "TGFB-Het": ["TGFBeta-Heterozygote"],
    "Sham": ["type of control sample"],
    "post-Sham": ["describes sample post sham"],
    "post-IR": ["describes sample post irradiation"],
    "wk": ["week"],
    "LCL": ["Lymphoblastoid Cell Line"],
    "GM15510": ["Lymphoblastoid Cell Line GM15510"],
    "RCCS": ["Rotary Cell Culture System"],
    "RAW2647cells": ["RAW 264.7 cell line"],
    "TK6cells": ["TK6 Lymphoblast Cell Line"],
    "cax1-1": ["cax1-1 transgenic line of Arabidopsis thaliana"],
    "SDR": ["Sprague Dawley Rats"],
    "56Fe": ["Iron isotope"],
    "C3H-He-Slc": ["C3H/He mice from Japan Slc, Inc."],
    "C57-6J-Jms-Slc": ["C57BL/6J Jms mice from Japan Slc, Inc."],
    "AJ-Jms-Slc A/J": ["Jms mice from Japan Slc, Inc"],
    "h": ["hour (Time)"],
    "Cs137": ["Caesium-137 isotope"],
    "Epi200MT": ["3-dimensional tissue model of human epidermis, MatTek Corporation, Ashland, MA"],
    "SMK": ["Smoker"],
    "nSMK": ["non-Smoker"],
    "um": ["micrometer"],
    "MCF10Acells": ["MCF10A cells"],
    "TGFB": ["Tumor Growth Factor Beta"],
    "X-ray": ["X-ray irradiation"],
    "AT": ["Adipose Tissue"],
    "Preg": ["Pregnant"],
    "Lac": ["Lactating"],
    "Hi-LET": ["High Linear Energy Transfer"],
    "Si": ["Silicon isotope"],
    "C3H-HeJ": ["C3H Heston mouse from Jackson Labs"],
    "d": ["day"],
    "K-12MG1655": ["strain K-12 MG1655"],
    "HBF": ["hyper-buoyancy flotation"],
    "VL": ["vastus lateralis"],
    "Rep": ["replicate"],
    "Hsap": ["Homo sapiens"],
    "Mmus": ["Mus musculus"],
    "shamIR": ["mock irradiation"],
    "Cb": ["cerebellum"],
    "Scer": ["Saccharomyces cerevisiae"],
    "BY4742": ["Strain of Saccharomyces cerevisiae"],
    "BY4742_FLO1": ["S. cerevisiae strain BY4742 over-expressing the FLO1 member of the Flo adhesin protein family"],
    "BY4742_FLO8": ["S. cerevisiae strain BY4742 over-expressing the FLO8 member of the Flo adhesin protein family"],
    "Cele": ["Caenorhabditis elegans"],
    "BMCs": ["bone marrow cells"],
    "BM": ["bone marrow"],
    "Euth": ["Euthasol"],
    "Ket-Xyl": ["Ketamine/Xylazine"],
    "ext1": ["RNA was extracted the same day organs were dissected from frozen carcasses"],
    "ext2": ["RNA was extracted on a later date Organs were dissected from frozen carcasses, flash frozen in (l)N2 and stored at -80C then"],
    "Lminus": ["Launch minus"],
    "Lplus": ["Launch plus"],
    "Rminus": ["Return minus"],
    "Rplus": ["Return plus"],
    "CO2": ["Carbon Dioxide"],
    "RLT": ["RNeasy Lysis Buffer"],
    "DSKN": ["Dorsal Skin"],
    "FSKN": ["Femoral Skin"],
    "F# ": ["mouse number from a spaceflight group"],
    "G#": ["mouse number from a ground control group"],
    "B# ": ["mouse number from a basal group"],
    "V# ": ["mouse number from a vivarium group"],
    "R1": ["Forward Read"],
    "R2": ["Reverse Read"],
    "JCwFOS": ["JAXA Chow with FOS"],
    "mon": ["month"],
    "y": ["year(s)"],
    "SP": ["spleen pool"],
    "MCC": ["MidiCAR centrifuge"],
    "MgSO4": ["magnesium sulfate"],
    "min": ["minute"],
    "Rotation": ["rotation"],
    "Hypocotyl": ["hypocotyl"],
    "HypocotylCC": ["Hypocotyl cell culture"],
    "PBLD": ["Peripheral Blood"],
    "In-FLT-CTRL": ["In-flight Control"],
    "PC": ["pipette centrifuge"],
    "Olat": ["Oryzias latipes"],
    "TGFP-ODsRed": ["Oryzias latipes (Japanese medaka) F1 fish of two closed colonies"],
    "OVY": ["Ovary"],
    "TES": ["Testis"],
    "INT": ["Intestines"],
    "NCTC-86": ["strain ATCC 4157 NCTC 86ug-mL concentration in micrograms per milliliter"],
    "Smut": ["Streptococcus mutans"],
    "ITS": ["internal transcribed spacer"],
    "Paer": ["Pseudomonas aeruginosa"],
    "RWV-V": ["Rotating Wall Vessel in veritical direction"],
    "RWV-H": ["Rotating Wall Vessel in horizontal direction"],
    "PA01": ["PAO1 strain - Pseudomonas aeruginosa"],
    "HMVEC-dBL": ["Human dermal microvascular endothelial cells"],
    "LPS": ["lipopolysaccharide"],
    "S-UHRR": ["Stratagene Universal Human Reference RNA"],
    "PTN-OSF1": ["transgenic mice overexpressing the osteogneic factor PTN/OSF1"],
    "DLD-1": ["DLD-1 cells epithelial, adherent cell line derived from a colorectal adenocarcinoma (Dukes type C)"],
    "MOLT-4": ["MOLT-4 cell line T lymphoblast, suspension cell line derived from an acute lymphoblastic leukemia"],
    "IMR90iPSCs": [" induced pluripotent stem cells derived from the IMR90 human cell line"],
    "CPCs": ["Cardiac progenitor cells"],
    "PhaB": ["Pharyngeal Bones"],
    "Cab": ["wild type Cab strain of Oryzias latipes"],
    "LC": ["Laboratory control"],
    "TLCs": ["Tcells lymphocyte"],
    "cGy": ["centigray"],
    "168": ["Strain of Bacillus subtilis"],
    "PBMCs": ["peripheral blood mononuclear cells"],
    "pip2Dclino": ["2D pipette clinostat"],
    "pipcent": ["pipette centrifuge"],
    "ALLCL": ["acute lymphoblastic leukemia cell line"],
    "CRCCL": ["colorectal cancer cell line"],
    "GF": ["Glovebox Freezer"],
    "CyroC": ["Cyrochiller"],
    "WCar": ["Whole Carcass"],
    "PCar": ["Partial Carcass"],
    "Esco": ["Euprymna scolopes"],
    "aposym": ["aposymbiotic"],
    "sym": ["symbiotic"],
    "HARV": ["high-aspect-ratio rotating wall vessel bioreactors"],
    "LO": ["Light Organ"],
    "UAMS-1": ["Strain of Staphylococcus aureus"],
    "Saur": ["Staphylococcus aureus"],
    "Mmar": ["Mycobacterium marinum"],
    "LHM4": ["Strain of Mycobacterium marinum"],
    "InsP-5-ptase": ["transgenic Arabidopsis thaliana"],
    "LLC Lewis": ["lung carcinoma"],
    "LLCtumor": ["Tumor derived from Lewis lung carcinoma cells"],
    "LLCcells": ["Lewis lung carcinoma cells"],
    "Trp53N-MG": ["Trp53 null mammary gland"],
    "B6. 129S2KrasLA1": ["B6.129S2-/Nci Mouse strain"],
    "Trp53N-MGT": ["Trp53 null mammary gland tumor"],
    "Drer": ["Danio rerio"],
    "PBLs": ["peripheral blood lymphocytes"],
    "AG01522": ["human fibroblasts AG01522 cells"],
    "ble": ["bleomycin"],
    "FBC": ["fibroblasts cells"],
    "Low-LET": ["Low Linear Energy Transfer"],
    "C57-6 C57BL/6": ["mouse from an unknown origin"],
    "cls": ["plant callus"],
    "T": ["tesla"],
    "MM2d": ["Arabidopsis thaliana MM2d cell line"],
    "Bsub": ["Bacillus subtilis"],
    "S288C": ["strain of Saccharomyces cerevisiae"],
    "HIR": ["Heavy Ion Radiation"],
    "TNR": ["Thermal Neutron Radiation"],
    "FNR": ["Fast Neutron Radiation"],
    "HSFA2-KO": ["a knockout line deficient in the gene encoding HSFA2 Arabidopsis thaliana"],
    "AB": ["Strain of Danio rerio"],
    "WN624": ["Strain of Bacillus subtilis"],
    "WN1106": ["Strain of Bacillus subtilis"],
    "HEBC3KT": ["human bronchial epithelial cell line"],
    "28Si": ["Si 28 isotope"],
    "Zone-I": ["region of root apex: 0.5 mm, root cap and meristematic zone"],
    "Zone-II": ["region of root apex: 1.5 mm, transition, elongation and growth terminating zone"],
    "Node3": ["node 3 of ISS"],
    "AHSFS": ["air handling system filter screen of ISS"],
    "SIEV": ["sieved"],
    "Batr": ["Bacillus atrophaeus"],
    "blank": ["no DNA or RNA added to extraction kit"],
    "PAS": ["passive aerosol sample"],
    "HBECs": ["human bronchial epithelial cells"],
    "2D": ["cells grown in 2D condition"],
    "3D": ["cells grown in 3D condition"],
    "TT": ["tetanus toxoid"],
    "noTT": ["tetanus toxoid control"],
    "ODNCpG": ["adjuvant treatment of a synthetic oligodeoxynucleotide (ODN) containing unmethylated CpG motifs (CpG)"],
    "noODNCpG": ["adjuvant treatment control"],
    "AG1522": ["normal human foreskin fibroblast cell line"],
    "HT1080": ["human fibrosarcoma cell line"],
    "RAD51": ["RAD51 gene"],
    "G1": ["G1 phase of cell cycle"],
    "G2": ["G2 phase of cell cycle"],
    "Asyn": ["Asynchronous cells"],
    "FirstSet": ["first set of animals (or samples) processed/preserved in a given day of operations"],
    "SecondSet": ["second set of animals (or samples) processed/preserved in a given day of operations"],
    "ThirdSet": ["third set of animals (or samples) processed/preserved in a given day of operations"],
    "FourthSet": ["fourth set of animals (or samples) processed/preserved in a given day of operations"],
    "CTRLSet": ["control set of animals (or samples) processed/preserved in a given day of operations"],
    "Styp": ["Salmonella typhimurium"],
    "SL1344": ["Salmonella enterica subsp. enterica serovar Typhimurium strain SL1344"],
    "dhfq": ["isogenic hfq deletion mutant"],
    "HT-29": ["human colorectal adenocarcinoma cell line with epithelial morphology"],
    "U937": ["human macrophage cell line established from a diffuse histiocytic lymphoma"],
    "3DCoC": ["3D co-culture model"],
    "LoopG": ["Loop Genomics"],
    "w1118": ["strain of Drosophila melanogaster"],
    "16S": ["16S rRNA gene"],
    "DFVS": ["dust filter of ventilation system"],
    "VAC": ["vacuum"],
    "INCd": ["incubated"],
    "arch": ["archaea"],
    "uni": ["universal"],
    "M# ": ["mouse number"],
    "S#": ["subject number"],
    "scWim": ["sample collected while inside module"],
    "scAem": ["sample collected after exiting module"],
    "scBem": ["sample collected before entering module"],
    "SKF": ["ion channel SKF-96365 inhibitorHRremoved Human Reads removed"],
    "Heat": ["treated with heat"],
    "noHeat": ["not treated with head"],
    "Anox": ["Anoxia"],
    "noAnox": ["not Anoxia"],
    "mid-age": ["middle-age"],
    "C57-6NIA": ["C57BL/6 mouse from National Institute of Aging"],
    "CUMS": ["chronic unpredictable mild stressors"],
    "Eves": ["Eruca vesicaria"],
    "CAAT": ["Controlled Artificial Ageing Treatment"],
    "cop1": ["cop1 gene"],
    "uvr8": ["uvr8 gene"],
    "C1": ["Cohort Control #1"],
    "C2": ["Cohort Control #2"],
    "~60": ["~60 {day}"],
    "~30": ["~30 {day}"],
    "0": ["0 {day}"],
    "~25": ["~25 {day}"],
    "~75": ["~75 {day}"],
    "7d":["7 {day}"],
}


from re import escape, search, sub
from itertools import count


GROUPREPLACE_OUTER_PATTERN = r'_\((?P<A>[^(]+)\)(v\((?P<B>[^(]+)\))?'
GROUPREPLACE_INNER_PATTERN = (r'^(' + r'|'.join(map(escape, sorted(
        GROUP_REPLACEMENT_OPTIONS.keys(), key=lambda s: len(s), reverse=True,
    ))) + r')((\s*[&_]\s*)|$)')
GROUPREPLACE_INNER_NONPATTERN = r'([^&_]+)(\s*[&_]\s*|$)'


def choose_group_replacement_option(subgroup):
    # here we'll look back onto the set of factor values we have;
    # result may be just `subgroup` or either of the replacement options
    return GROUP_REPLACEMENT_OPTIONS[subgroup][0]


def groupreplace_column(column, maxdepth=128):
    def _g_groupreplace(group):
        reps, tail, counter = [], group, count()
        while tail and (next(counter) < maxdepth):
            submatch = search(GROUPREPLACE_INNER_PATTERN, tail)
            subgroup = submatch.group(1) if submatch else None
            if subgroup:
                reps.append(choose_group_replacement_option(subgroup))
                tail = tail[len(submatch.group(0)):]
            else:
                subnonmatch = search(GROUPREPLACE_INNER_NONPATTERN, tail)
                subnongroup = subnonmatch.group(1) if subnonmatch else None
                if subnongroup:
                    reps.append(subnongroup.rstrip())
                    tail = tail[len(subnonmatch.group(0)):]
                else:
                    reps.append(tail)
                    tail = ""
        return " & ".join(reps)
    def _replfactory(match):
        _g = match.groupdict()
        if _g["B"]:
            return f"_({_g_groupreplace(_g['A'])})v({_g_groupreplace(_g['B'])})"
        else:
            return f"_({_g_groupreplace(_g['A'])})"
    return sub(GROUPREPLACE_OUTER_PATTERN, _replfactory, column)


TEST_COLUMNS = [
    "Group.Mean_(Col-0_FLT)",
    "Log2FC_(Col-0FLT)v(Col-0_GC_BOO)",
    "Log2FC_(Col-0_FLT)v(Col-0_BOO & GC)",
]


for c in TEST_COLUMNS:
    print(c, "->", groupreplace_column(c))
